- name: assert
  ansible.builtin.assert:
    that:
      - rpi_addr
      - rpi_cidr_allow
      - rpi_domain
      - rpi_name
    fail_msg: one or more variables are required

- name: install
  ansible.builtin.apt:
    pkg:
      - unbound

- name: config
  ansible.builtin.template:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    validate: /usr/sbin/unbound-checkconf %s
    backup: yes
  notify:
    - service

- name: unit
  ansible.builtin.copy:
    src: unbound.service.d
    dest: /etc/systemd/system/
  notify:
    - systemd

- name: service
  ansible.builtin.service:
    name: unbound
    state: started
