- name: install
  ansible.builtin.apt:
    pkg:
      - unbound

- name: config
  ansible.builtin.template:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    validate: /usr/sbin/unbound-checkconf %s
    backup: yes
  notify:
    - service

- name: service
  ansible.builtin.service:
    name: unbound
    state: started
