- name: install
  ansible.builtin.apt:
    pkg:
      - openssh-server

- name: config
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    backup: yes
  notify:
    - service

- name: service
  ansible.builtin.service:
    name: sshd
    enabled: yes
    state: started
