- name: assert
  ansible.builtin.assert:
    that:
      - rpi_addr
    fail_msg: one or more variables are required

- name: install
  ansible.builtin.apt:
    pkg:
      - openssh-server

- name: config
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - service

- name: service
  ansible.builtin.service:
    name: sshd
    enabled: yes
    state: started
